### PR TITLE
feat: accept Base64 too

### PR DESCRIPTION
**Pull request by ludufre**
Hi, I added support to Data Url (base64 image) as param.

Captura de Tela 2023-07-06 às 14 06 25
Captura de Tela 2023-07-06 às 14 06 32

### CODE REVIEW

**Comment by jroeglin** [comment]
We are interested in this feature please merge.

**Comment by ludufre** [comment]
Hi @dtarnawsky I ended up forgetting about this PR. Are you referring to any fixes I need to do? I'm lost...

**Comment by ludufre** [comment]
Hi @dtarnawsky Is there anything I can do to make this functionality accepted? Or is it really not interesting?

**Comment by dtarnawsky** [comment]
@ludufre , It looks like the review comments were addressed but there wasn't a reply on this thread so I assumed it wasn't addressed.

I'll do some quick testing and will include this PR in a v6 release.

**Comment by dtarnawsky** [comment]
@ludufre Are you able to resolve the conflicts on the README.md?

**Pull request closed without merging**
